name: GitHub Pages

on:
  push:
    branches: 
      - '**'

  release:
    types: [published]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install cleanlab
        run: pip install -e .

      - name: Install dependencies
        run: python3 -m pip install -r docs/requirements.txt

      - name: Run Sphinx with sphinx-multiversion wrapper - branch trigger
        if: ${{ github.ref_type == 'branch' }}
        run: sphinx-multiversion docs/source cleanlab-docs -D smv_branch_whitelist=${{ github.ref_name }} -D smv_tag_whitelist=None

      - name: Run Sphinx with sphinx-multiversion wrapper - tag trigger
        if: ${{ github.ref_type == 'tag' }}
        run: sphinx-multiversion docs/source cleanlab-docs -D smv_branch_whitelist=None -D smv_tag_whitelist=${{ github.ref_name }}

      - name: Get latest stable release
        id: stable_release
        continue-on-error: true
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ${{ github.repository_owner }}
          repo: cleanlab
          excludes: prerelease, draft

      - name: Find and replace "placeholder_version_number" in verisioning.js
        if: ${{ steps.stable_release.outcome == 'success' }}
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "placeholder_version_number"
          replace: ${{ steps.stable_release.outputs.release }}
          include: "docs/source/_templates/versioning.js"

      - name: Find and replace "placeholder_commit_hash" in verisioning.js
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "placeholder_commit_hash"
          replace: ${{ github.sha }}
          include: "docs/source/_templates/versioning.js"

      - name: Copy versioning JS file to cleanlab-docs/
        run: |
          cp docs/source/_templates/versioning.js cleanlab-docs/versioning.js

      - name: Find and replace "stable_url" in redirect-to-stable.html
        if: ${{ github.ref_type == 'tag' && steps.stable_release.outcome == 'success' }}
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "stable_url"
          replace: ${{ env.DOCS_SITE_URL }}${{ steps.stable_release.outputs.release }}/index.html
          include: "docs/source/_templates/redirect-to-stable.html"

      - name: Copy redirecting HTML file to cleanlab-docs/ and cleanlab-docs/stable
        if: ${{ github.ref_type == 'tag' }}
        run: |
          mkdir cleanlab-docs/stable
          cp docs/source/_templates/redirect-to-stable.html cleanlab-docs/stable/index.html
          cp docs/source/_templates/redirect-to-stable.html cleanlab-docs/index.html

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: ${{ github.repository_owner }}/cleanlab-docs
          publish_branch: master
          publish_dir: cleanlab-docs
          keep_files: true
